log:
  debug: false
apis:
  grpc:
    address: "0.0.0.0:9100"
    tls:
      caPool: "/secrets/public/rootca.crt"
      keyFile: "/secrets/private/cert.key"
      certFile: "/secrets/public/cert.crt"
      clientCertificateRequired: true
    authorization:
      authority: ""
      audience: ""
      http:
        maxIdleConns: 16
        maxConnsPerHost: 32
        maxIdleConnsPerHost: 16
        idleConnTimeout: 30s
        timeout: 10s
        tls:
          caPool: "/secrets/public/rootca.crt"
          keyFile: "/secrets/private/cert.key"
          certFile: "/secrets/public/cert.crt"
          useSystemCAPool: false
clients:
  eventBus:
    # number of routines to process events in projection
    goPoolSize: 16
    nats:
      url: nats://localhost:4222
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  resourceAggregate:
    grpc:
      address: ""
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false
  resourceDirectory:
    grpc:
      address: ""
      keepAlive:
        time: 10s
        timeout: 20s
        permitWithoutStream: true
      tls:
        caPool: "/secrets/public/rootca.crt"
        keyFile: "/secrets/private/cert.key"
        certFile: "/secrets/public/cert.crt"
        useSystemCAPool: false