language: generic
dist: bionic
services:
  - docker-bionic

jobs:
  include:
    - stage: test
      name: "Test"
      if: type = pull_request
      script:
        - make test
    - stage: test_publish
      name: "Test & Publish"
      if: branch = master AND type != pull_request AND commit_message !~ \[doc\]
      script:
        - make test
        - bash <(curl -s https://codecov.io/bash)
        - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - make push
    - stage: docs
      name: "Documentation"
      node_js:
        - lts/*
      install:
        - yarn install
      script:
        - yarn docs:build
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist
        github_token: $GITHUB_TOKEN
        keep_history: true
        fqdn: gocf.dev
        on:
          branch: master
