name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    tags:
      - '*'
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set commit message
        run: echo "COMMIT_MESSAGE=`git log --format=%B -n 1`" >> $GITHUB_ENV

      - name: Run a test
        if: ${{ !startsWith("[doc]", env.COMMIT_MESSAGE) }}
        run: make test
        
      - name: Publish the coverage
        if: ${{ !startsWith("[doc]", env.COMMIT_MESSAGE) }}
        run: bash <(curl -s https://codecov.io/bash)

      - name: Set latest tag
        if: ${{ !startsWith("[doc]", env.COMMIT_MESSAGE) }}
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Publish docker images
        if: ${{ !startsWith("[doc]", env.COMMIT_MESSAGE) }}
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin && make push LATEST_TAG=${{ env.RELEASE_VERSION }}


